--CREATE DATABASE HOTEL1
--USE HOTEL1

--CREATE TABLE ROOMTYPE(
--ID INT PRIMARY KEY IDENTITY,
--[NAME] NVARCHAR(50)
--)

--CREATE TABLE ROOMSTATUS(
--ID INT PRIMARY KEY IDENTITY,
--[STATUS] BIT DEFAULT 0
--)

--CREATE TABLE ROOM(
--ID INT PRIMARY KEY IDENTITY,
--ROOMTYPEID INT REFERENCES ROOMTYPE(ID),
--STATUSID INT REFERENCES ROOMSTATUS(ID)
--)

--CREATE TABLE CUSTOMER(
--ID INT PRIMARY KEY IDENTITY,
--FULLNAME NVARCHAR(100),
--EMAIL NVARCHAR(100),
--[ADDRESS] NVARCHAR(100),
--PHONE NVARCHAR(100),
--COUNTRY NVARCHAR(70)
--)

--CREATE TABLE RESERVATION(
--ID INT PRIMARY KEY IDENTITY,
--CUSTOMERID INT REFERENCES CUSTOMER(ID),
--ROOMID INT REFERENCES ROOM(ID),
--RESERVATIONDATE DATE
--)


--CREATE TABLE PAYMENT(
--ID INT PRIMARY KEY IDENTITY,
--RESERVATIONID INT REFERENCES RESERVATION(ID)
--)

--CREATE TABLE SPENDINGS(
--ID INT PRIMARY KEY IDENTITY,
--PAYMENTID INT REFERENCES PAYMENT(ID),
--[MONEY] DECIMAL
--)

--INSERT INTO ROOMTYPE VALUES('Single'),('Double'),('King')
--INSERT INTO ROOMSTATUS VALUES(1),(0)
--INSERT INTO ROOM VALUES(2,2)
--INSERT INTO CUSTOMER VALUES('Emil Hacizade','emil_hacizade@mail.ru','Qaracuxur','05345532341','Azerbaycan')
--INSERT INTO RESERVATION VALUES(2,5,'2022-04-24'),(1,7,'2022-04-10'),(3,8,'2022-03-08')
--INSERT INTO PAYMENT VALUES(3),(1)
--INSERT INTO SPENDINGS VALUES(2,200),(1,500),(3,600)


--- VIEW ----

--CREATE VIEW MYVIEW
--AS
--SELECT FULLNAME,EMAIL,[ADDRESS]
--FROM CUSTOMER

--SELECT * FROM MYVIEW

-- PROCEDURE -- 

--CREATE PROCEDURE HOTELPROCEDURE @RoomTypeId INT
--AS
--SELECT [NAME] FROM ROOMTYPE WHERE @RoomTypeId = ROOMTYPE.ID

--EXEC HOTELPROCEDURE 3


--CREATE PROCEDURE SHOWALLSPENDINGS
--AS
--SELECT [MONEY] FROM SPENDINGS

--EXEC SHOWALLSPENDINGS

-- FUNCTION -- 

--CREATE FUNCTION SHOWPHONE(@CUSTOMID INT)
--RETURNS INT
--AS
--BEGIN
--	DECLARE @PHONENUM NVARCHAR(50)
--	SELECT @PHONENUM = PHONE FROM CUSTOMER WHERE CUSTOMER.ID = @CUSTOMID
--	RETURN @PHONENUM
--END

--SELECT DBO.SHOWPHONE(4) AS PHONENUM

-- TRIGGER

--CREATE TRIGGER SHOWUPDATEDINFO
--ON CUSTOMER
--AFTER INSERT
--AS
--BEGIN
--	SELECT * FROM CUSTOMER
--END


--INSERT INTO CUSTOMER VALUES('Ali Valiyev','ali2000@mail.ru','Xetai','0552424222','Azerbaycan')