--CREATE DATABASE TURBOAZ

--USE TURBOAZ




CREATE TABLE MARKA(
ID INT PRIMARY KEY IDENTITY,
[NAME] NVARCHAR(50)
)

CREATE TABLE MODEL(
ID INT PRIMARY KEY IDENTITY,
[NAME] NVARCHAR(50),
MARKAID INT REFERENCES MARKA(ID)
)


CREATE TABLE BANNOVU(
ID INT PRIMARY KEY IDENTITY,
[NAME] NVARCHAR(50)
)

CREATE TABLE YURUSH(
ID INT PRIMARY KEY IDENTITY,
KM INT,
[NAME] NVARCHAR(50)
)

CREATE TABLE RENG(
ID INT PRIMARY KEY IDENTITY,
[NAME] NVARCHAR(50)
)

CREATE TABLE QIYMET(
ID INT PRIMARY KEY IDENTITY,
QIYMET FLOAT,
MEZENNE NVARCHAR(20)
)


CREATE TABLE YANACAQNOVU(
ID INT PRIMARY KEY IDENTITY,
[NAME] NVARCHAR(50)
)

CREATE TABLE OTURUCU(
ID INT PRIMARY KEY IDENTITY,
[NAME] NVARCHAR(50)
)

CREATE TABLE SURETLERQUTUSU(
ID INT PRIMARY KEY IDENTITY,
[NAME] NVARCHAR(50)
)

CREATE TABLE BURAXILISHILI(
ID INT PRIMARY KEY IDENTITY,
IL INT
)

CREATE TABLE MUHERRIKHECMI(
ID INT PRIMARY KEY IDENTITY,
HECM INT
)

CREATE TABLE MUHERRIKGUCU(
ID INT PRIMARY KEY IDENTITY,
GUC INT
)

CREATE TABLE ELAVEMELUMAT(
ID INT PRIMARY KEY IDENTITY,
TEXT NVARCHAR(500)
)

CREATE TABLE AVTOMOBILINTECHIZATI(
ID INT PRIMARY KEY IDENTITY,
YUNGULLEHIMLIDISKLER BIT DEFAULT 0,
[ABS] BIT DEFAULT 0,
LYUK BIT DEFAULT 0,
KONDISIONER BIT DEFAULT 0,
DERISALON BIT DEFAULT 0
)

CREATE TABLE ELAN(
ID INT PRIMARY KEY IDENTITY,
[NAME] NVARCHAR(50),
MODEL INT REFERENCES MODEL(ID),
BANNOVUID INT REFERENCES BANNOVU(ID),
YURUSHID INT REFERENCES YURUSH(ID),
RENGID INT REFERENCES RENG(ID),
QIYMETID INT REFERENCES QIYMET(ID),
YANACAQNOVUID INT REFERENCES YANACAQNOVU(ID),
OTURUCUID INT REFERENCES OTURUCU(ID),
SURETLERQUTUSUID INT REFERENCES SURETLERQUTUSU(ID),
BURAXILISHILIID INT REFERENCES BURAXILISHILI(ID),
MUHERRIKHECMIID INT REFERENCES MUHERRIKHECMI(ID),
MUHERRIKGUCUID INT REFERENCES MUHERRIKGUCU(ID),
ELAVEMELUMATID INT REFERENCES ELAVEMELUMAT(ID),
AVTOMOBILINTECHIZATIID INT REFERENCES AVTOMOBILINTECHIZATI(ID)
)

INSERT INTO MARKA VALUES('Aston Martin'),('BMW'),('Mercedes'),('Nissan')
INSERT INTO MODEL VALUES('Vantage',1),('M8',2),('S 63 AMG',3),('Maxima',4)
INSERT INTO BANNOVU VALUES('Kupe'),('Hetchbek'),('SUV'),('Sedan')